CREATE DATABASE SENAI_BUGMUSIC_TARDE;

USE SENAI_BUGMUSIC_TARDE;

CREATE TABLE GENERO(
	
	ID INT IDENTITY PRIMARY KEY
	,NOMES_GENEROS	VARCHAR(255) NOT NULL

);

CREATE TABLE CANTORES(

	ID INT IDENTITY PRIMARY KEY
	,NOME_CANTOR VARCHAR(255) NOT NULL

);

CREATE TABLE BANDAS(

	ID INT IDENTITY PRIMARY KEY
	,NOME_BANDA VARCHAR(255) NOT NULL
	,ID_GENERO INT FOREIGN KEY REFERENCES GENERO(ID)
);

CREATE TABLE BANDAS_CANTORES(

	ID_CANTOR INT FOREIGN KEY REFERENCES CANTORES(ID)
	,ID_BANDA INT FOREIGN KEY REFERENCES BANDAS(ID)
);

CREATE TABLE ALBUNS(

	ID INT IDENTITY PRIMARY KEY
	,NOME_ALBUNS VARCHAR(255) NOT NULL
	,ID_BANDA INT FOREIGN KEY REFERENCES BANDAS(ID)
);

CREATE TABLE MUSICAS(
	
	ID INT IDENTITY PRIMARY KEY 
	,NOME_MUSICAS VARCHAR(255) NOT NULL
	,ID_ALBUN INT FOREIGN KEY REFERENCES ALBUNS(ID)
);
