CREATE DATABASE SENAI_CLINICA_PET_TARDE;

USE SENAI_CLINICA_PET_TARDE;

CREATE TABLE CLINICA(

	ID INT IDENTITY PRIMARY KEY
	,NOME_CLINICA VARCHAR(255) NOT NULL
	,ENDERECO VARCHAR(255) NOT NULL
);

CREATE TABLE TIPO_PET(
	
	ID INT IDENTITY PRIMARY KEY
	,DESCRICAO VARCHAR(255)NOT NULL
);

CREATE TABLE DONOS(

	ID INT IDENTITY PRIMARY KEY
	,NOME_DONO VARCHAR(255)NOT NULL
);


CREATE TABLE RACAS(
	
	ID INT IDENTITY PRIMARY KEY
	,DESCRICAO_RACAS VARCHAR(255)NOT NULL 
	,ID_TIPO_PET INT FOREIGN KEY REFERENCES TIPO_PET(ID)
);

CREATE TABLE VETERINARIOS(

	ID INT IDENTITY PRIMARY KEY
	,CRMV CHAR(6) NOT NULL
	,NOME_VETERINARIO VARCHAR(255) NOT NULL
);

-- alter table permite que vc faça mudanças na sua tabela 
alter table veterinarios add ID_CLINICA INT FOREIGN KEY REFERENCES CLINICA(ID)

CREATE TABLE PETS(

	ID INT IDENTITY PRIMARY KEY 
	,NOME_PET VARCHAR(255) NOT NULL
	,DATA_NASCIMENTO DATETIME NOT NULL
	,ID_RACA_PET INT FOREIGN KEY REFERENCES RACAS(ID)
);

ALTER TABLE PETS ADD ID_DONO INT FOREIGN KEY REFERENCES DONOS(ID)

CREATE TABLE ATENDIMENTOS(

	ID INT IDENTITY PRIMARY KEY 
	,ID_PET INT FOREIGN KEY REFERENCES PETS(ID)
	,ID_VET INT FOREIGN KEY REFERENCES VETERINARIOS(ID)
	,DESCRICAO_PET VARCHAR(255) NOT NULL
	,DATA_ATENDIMENTO DATETIME 
);

/*
ALTER TABLE "nome_tabela" PARA FAZER ALGUMA ALTERAÇÃO NA TABELA JA CRIADA 
Adicionar uma coluna: ADD "coluna 1" "tipo de dados para a coluna 1"
Remover uma coluna: DROP "coluna 1"
Alterar o nome de uma coluna: CHANGE "antigo nome da coluna" "novo nome da coluna" "tipo de dados para novo nome da coluna"
Alterar o tipo de dados de uma coluna: MODIFY "coluna 1" "novo tipo de dados"
*/