--CRIA BANCO DE DADOS
CREATE DATABASE SENAI_SVIGUFO_TARDE;

--USA AS INTRUÇÕES SQL NO BANCO INFORMADO
USE SENAI_SVIGUFU_TARDE;
/*
	CREAT TABLE <NOMETABELA>CRIA UMA NOVA TABELA 
	IDENTITY - AUTO-INCREMENTO
	PRIMARY KEY - DEFINE QUE O CAMPO SERÁ UMA CHAVE PRIMEARIA 
	NOT NULL - NÃO ACEITA VALORES NULOS 
	UNIQUE DEFINE QUE O CAMPO TERA UM VALOR UNICO, NÃO PODE TER VALORES REPETIDOS 
	VARCHAR E UM TIPO STRING QUE DEFINE A QUANTIDADE QUE VAI TER NA SUA VARIAVEL
	*/
CREATE TABLE TIPOS_EVEVNTOS(
  ID INT IDENTITY PRIMARY KEY
  , TITULO  VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE INSTITUICOES(
	ID INT IDENTITY PRIMARY KEY
	,RAZAOSOCIAL VARCHAR(255) NOT NULL
	,NOME_FANTASIA VARCHAR(255) 
	,CNPJ CHAR(14) NOT NULL UNIQUE
	,LOGRADOURO VARCHAR(255) NOT NULL
	,CEP CHAR(8) NOT NULL
	,UF CHAR(2) NOT NULL 
	,CIDADE VARCHAR(255) NOT NULL
);

CREATE TABLE EVENTOS(
	ID INT IDENTITY PRIMARY KEY
	,TITULO VARCHAR(255) NOT NULL
	,DESCRICAO TEXT --PARA CAMPOS COM GRANDE QUANTIDADE DE DADOS 
	,DATA_EVENTO DATETIME NOT NULL --CAMPOS DO TIPO DATA E HORA 
	,ACESSO_LIVRE BIT DEFAULT (1) -- PARA VALORES 0 E 1, 0 FALSE 1 TRUE,  
	,ID_TIPO_EVENTO INT 
	,ID_INSTITUICAO INT 
	-- CRIA UMA CHAVE ESTRANGEIRA E DEFINE QUE O CAMPO ESTA RELACIONADO A TABELA(CAMPO)
	,FOREIGN KEY (ID_TIPO_EVENTO) REFERENCES TIPOS_EVEVNTOS(ID)
	,FOREIGN KEY (ID_INSTITUICAO) REFERENCES INSTITUICOES(ID)
);

CREATE TABLE USUARIO(

	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) NOT NULL
	,EMAIL VARCHAR(255) NOT NULL UNIQUE
	,SENHA VARCHAR(100) NOT NULL
	,TIPO_USUARIO VARCHAR(100) NOT NULL	

);

CREATE TABLE CONVITES(

	ID INT IDENTITY PRIMARY KEY
	,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIO(ID)
	,ID_EVENTO INT FOREIGN KEY REFERENCES EVENTOS(ID)
	,SITUACAO CHAR(1) 

);